name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release on crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish
